name: Overlog_CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Linting
      run: |
        pylint overlog.py
        pylint frontend/
        pylint backend/
    - name: Test with pytest
      run: |
        pytest
    - name: Check if code is Blacked
      run: |
        black -l 79 --check overlog.py
        black -l 79 --check frontend/
        black -l 79 --check backend/
